"""empty message

Revision ID: 3543111007c6
Revises: f133983c5281
Create Date: 2024-10-13 16:34:21.599505

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3543111007c6'
down_revision: Union[str, None] = 'f133983c5281'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('timer', sa.Integer()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'timer')
    # ### end Alembic commands ###
